name: Go

on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.14', '1.19' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: 'driver-go'
      - name: checkout TDengine
        uses: actions/checkout@v3
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '3.0'
      - name: checkout taosAdapter
        uses: actions/checkout@v3
        with:
          repository: 'taosdata/taosadapter'
          path: 'taosadapter'
          ref: 'enh/TD-24019'

      - name: install TDengine
        run: |
          cd TDengine
          mkdir debug
          cd debug
          sudo apt-get install libgflags-dev
          cmake .. -DBUILD_JDBC=false -DBUILD_TEST=off
          make -j2
          sudo make install

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: build taosAdapter
        run: cd ./taosadapter && go build

      - name: shell
        run: |
          cat >start.sh<<EOF 
          ulimit -n 65535 && TAOS_SUPPORT_VNODES=256 taosd
          EOF

      - name: taosd
        run: nohup sudo sh ./start.sh &

      - name: start taosadapter
        run: cd ./taosadapter && sudo ./taosadapter &

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('driver-go/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Test
        run: cd ./driver-go && go test -v ./...
