name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.17' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'driver-go'
      - name: checkout TDengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '3.0'
          submodules: 'recursive'

      - name: install TDengine
        run: cd TDengine && git submodule update --init --recursive && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=false -DBUILD_HTTP=false && make && sudo make install

      - name: start taosd
        run: ulimit -a && ulimit -n 999999 && ulimit -a && nohup sudo taosd &

      - name: start taosadapter
        run: nohup sudo taosadapter &

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        run: cd ./driver-go && go test -v ./...
